apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstoredb-pvc
  namespace: eventstoredb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust based on your storage needs
