apiVersion: v1
kind: Service
metadata:
  name: eventstoredb
  namespace: eventstoredb
spec:
  clusterIP: None
  selector:
    app: eventstoredb
  ports:
    - name: http
      port: 2113
      targetPort: 2113
